# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
#Importar numpy
import numpy as np

In [3]:
#creo un array de ceros
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [4]:
array_diez=np.zeros(10)
array_diez[5]=10
print(array_diez)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [5]:
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
array_8_10=np.arange(9).reshape(3,3)
print(array_8_10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
array_100=np.random.randn(100)
print(array_100)

[ 2.60318412 -0.36360226  0.70996889 -0.30650157  0.20096866 -0.61918002
 -0.82418409  1.24988204 -1.37740035  0.41855419  2.29673314  0.37574964
 -1.3707105  -1.30484001  1.12614637  0.73013453 -1.98469588 -0.61353386
 -0.07633306  0.60790859  2.27582887 -3.52138686  0.18721976  0.34102879
 -0.56086063  1.52511142 -0.51791318  0.18214047  0.41719109  0.48794405
 -1.49716002  0.06957293  0.40928171  0.3977111  -0.60712236  0.51792456
 -0.60285165  0.79046887  1.68840232 -1.10582195 -0.48348126  0.41559794
  0.37981972 -0.92078097  0.71887449 -0.36515386 -0.08129274  0.05496621
 -1.00725746 -0.71545386 -1.30348178  1.53500914  0.97297894  0.92568206
 -0.34506905 -0.15570538  0.85106563 -1.72490348 -0.80409619  0.3648759
 -1.70857726  0.643514   -0.60189478  1.12356049 -1.83676881  0.22114627
 -1.17763328  1.39673765 -0.35759436 -1.0804137  -0.53989292  0.82108536
 -0.77216995 -1.57430037 -0.03476223 -1.74157254 -0.8523105  -0.27938693
 -0.32644059 -1.7876119  -1.35416976 -0.01490358 -1.

In [13]:
array_media=np.mean(array_100)
print(array_media)

array_varianza=np.var(array_100)
print(array_varianza)

-0.14916040264445574
1.1451702220503859


In [16]:
array_100_sum=np.sum(array_100)/[len(array_100)]
print(array_100_sum)

[-0.1491604]


In [18]:
array_100_varianza=np.sum((array_100-np.mean(array_100))**2)/[len(array_100)]
print(array_100_varianza)

[1.14517022]


In [17]:
array_random = np.random.randn (100)
print(array_random)

[ 7.83592348e-01 -1.66185107e-02 -8.22906706e-01 -5.19369195e-01
 -3.47930661e-01  1.25986186e+00 -1.45865322e+00  2.45372163e-03
 -1.40270306e+00 -2.73816115e-01  1.62544056e+00  1.85648679e+00
 -1.10875128e+00 -1.26763235e+00  4.28881389e-01  7.02789955e-02
  7.20495608e-01  1.47531230e+00  1.53934662e+00 -6.87547354e-01
 -1.70558192e+00 -2.18442745e+00  5.30247762e-01  1.14389733e+00
  3.03455728e-01 -1.98749980e-02 -1.76266962e-02  2.70146210e-01
 -1.73748892e-01  5.87706790e-01 -1.07942444e+00  9.90198524e-01
 -1.30508303e+00 -6.80179899e-01  9.05750160e-01 -4.03266136e-01
 -6.25007387e-01 -2.34291066e+00 -1.27771254e+00 -1.86686118e-01
  1.80515110e-01 -7.08821650e-01  3.87677492e-01 -6.92721852e-01
  2.14101208e-01 -8.62541507e-01 -8.52289911e-01  1.60525065e-01
  1.44856172e+00  5.74084340e-01 -5.46149376e-01  2.52012593e-01
  9.68398178e-01 -1.97987759e-01  3.81610594e-01 -1.11579009e-01
 -1.69128629e+00  3.20218169e-01  9.10715557e-01  1.01905065e+00
 -8.63699831e-01 -1.16744